#!/bin/bash
set -e

case "$1" in
    remove|purge)
        systemctl stop    ipu7-camera-dynamic 2>/dev/null || true
        systemctl disable ipu7-camera-dynamic 2>/dev/null || true
        ;;
esac

#DEBHELPER#
